In [ ]:
import numpy as np

In [ ]:
A = np.array([[-3, 1], [-1, 1], [1, 1], [3, 1]])
print(A)

[[-3  1]
 [-1  1]
 [ 1  1]
 [ 3  1]]


In [ ]:
b = np.array([-1, -1, 3, 3])

In [ ]:
At = A.transpose()
print(At)

[[-3 -1  1  3]
 [ 1  1  1  1]]


In [ ]:
AtA = At @ A
print(AtA)

Atb = At @ b
print(Atb)

AtA_inv = np.linalg.inv(AtA)
print(AtA_inv)

[[20  0]
 [ 0  4]]
[16  4]
[[0.05 0.  ]
 [0.   0.25]]


In [ ]:
xx = AtA_inv @ Atb
print(xx)

[0.8 1. ]


In [ ]:
bb = A @ x
print(bb)

[-1.4  0.2  1.8  3.4]
